#!/bin/bash

rm -f tmp.pyj
for file in `ls *.pyj | sort -n`; do
	content=`cat $file`
	printf "console.time('%s')\n%s\nconsole.timeEnd('%s')" "$file" "$content" "$file" > tmp.pyj
	rapydscript tmp.pyj > tmp.js && node tmp.js
done
